{
  CONSTRUCTOR_ID: 1957577280,
  SUBCLASS_OF_ID: 2331323052,
  className: 'Updates',
  classType: 'constructor',
  updates: [
    {
      CONSTRUCTOR_ID: 1318109142,
      SUBCLASS_OF_ID: 2676568142,
      className: 'UpdateMessageID',
      classType: 'constructor',
      id: 1,
      randomId: [Integer]
    },
    {
      CONSTRUCTOR_ID: 1666927625,
      SUBCLASS_OF_ID: 2676568142,
      className: 'UpdateChannel',
      classType: 'constructor',
      channelId: [Integer]
    },
    {
      CONSTRUCTOR_ID: 2452516368,
      SUBCLASS_OF_ID: 2676568142,
      className: 'UpdateReadChannelInbox',
      classType: 'constructor',
      flags: 0,
      folderId: null,
      channelId: [Integer],
      maxId: 1,
      stillUnreadCount: 0,
      pts: 2
    },
    {
      CONSTRUCTOR_ID: 1656358105,
      SUBCLASS_OF_ID: 2676568142,
      className: 'UpdateNewChannelMessage',
      classType: 'constructor',
      message: [Object],
      pts: 2,
      ptsCount: 1
    }
  ],
  users: [
    {
      CONSTRUCTOR_ID: 1262928766,
      SUBCLASS_OF_ID: 765557111,
      className: 'User',
      classType: 'constructor',
      flags: 33636395,
      self: false,
      contact: false,
      mutualContact: false,
      deleted: false,
      bot: true,
      botChatHistory: false,
      botNochats: true,
      verified: false,
      restricted: false,
      min: false,
      botInlineGeo: false,
      support: false,
      scam: false,
      applyMinPhoto: true,
      fake: false,
      botAttachMenu: false,
      premium: false,
      attachMenuEnabled: false,
      flags2: 4112,
      botCanEdit: false,
      closeFriend: false,
      storiesHidden: false,
      storiesUnavailable: true,
      contactRequirePremium: false,
      botBusiness: false,
      botHasMainApp: false,
      id: [Integer],
      accessHash: [Integer],
      firstName: 'Group',
      lastName: null,
      username: 'GroupAnonymousBot',
      phone: null,
      photo: [Object],
      status: null,
      botInfoVersion: 3,
      restrictionReason: null,
      botInlinePlaceholder: null,
      langCode: null,
      emojiStatus: null,
      usernames: null,
      storiesMaxId: null,
      color: null,
      profileColor: null,
      botActiveUsers: 16509,
      botVerificationIcon: null
    }
  ],
  chats: [
    {
      CONSTRUCTOR_ID: 3758725303,
      SUBCLASS_OF_ID: 3316604308,
      className: 'Channel',
      classType: 'constructor',
      flags: 286977,
      creator: true,
      left: false,
      broadcast: false,
      verified: false,
      megagroup: true,
      restricted: false,
      signatures: false,
      min: false,
      scam: false,
      hasLink: false,
      hasGeo: false,
      slowmodeEnabled: false,
      callActive: false,
      callNotEmpty: false,
      fake: false,
      gigagroup: false,
      noforwards: false,
      joinToSend: false,
      joinRequest: false,
      forum: false,
      flags2: 12,
      storiesHidden: false,
      storiesHiddenMin: true,
      storiesUnavailable: true,
      signatureProfiles: false,
      id: [Integer],
      accessHash: [Integer],
      title: 'prueba',
      username: null,
      photo: [Object],
      date: 1773077390,
      restrictionReason: null,
      adminRights: [Object],
      bannedRights: null,
      defaultBannedRights: [Object],
      participantsCount: null,
      usernames: null,
      storiesMaxId: null,
      color: null,
      profileColor: null,
      emojiStatus: null,
      level: null,
      subscriptionUntilDate: null,
      botVerificationIcon: null
    }
  ],
  date: 1773077389,
  seq: 0
}